### ISSUE TITLE
liquid error: memory limits exceeded

### ISSUE THREAD

**Issue by plisvb** [zakhardage/Shopify-Wish-List#7]
So I've been testing my wishlist function for months now and I've run into a wall because of the # of tags used for one user.  Any account page that I tried to access for that user was not accessible and I got the following error message "liquid error: memory limits exceeded".

After checking the user's admin, I saw a lot of tags (I didn't count them unfortunately) but after removing the tags with x's or multiple x's all worked fine.  I have two questions:

1) This memory limits exceeded applies only to that one user right?  Or will all users run into this problem?
2) Is there anyway to have a kind of trash collector that purges all x'd out tags?

Thanks

**Comment by zakhardage** [comment]
Thanks for the catch -- I figured that could happen, just hadn't heard a report of it yet. I don't have a non-app solution (other than a support link on the site).

This should only apply to the one user because the loop only runs through that one user's tags.
I think the real solution is to write an app that can delete tags and not just a form that adds to them.

I'll update the repository with your notes. Thanks again!
